# Generated by Django 6.0.4 on 2026-04-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientprofile_blood_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fhir_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fhir_resource_id',
            field=models.CharField(blank=True, help_text='FHIR Appointment resource ID from FHIR server', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fhir_sync_error',
            field=models.TextField(blank=True, help_text='Error message if FHIR sync failed'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fhir_sync_status',
            field=models.CharField(choices=[('pending', 'Pending FHIR Sync'), ('synced', 'Synced to FHIR'), ('failed', 'FHIR Sync Failed')], default='pending', help_text='Status of sync to FHIR server', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='fhir_resource_id',
            field=models.CharField(blank=True, help_text='FHIR Practitioner resource ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='fhir_resource_id',
            field=models.CharField(blank=True, help_text='FHIR Patient resource ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fhir_resource_id',
            field=models.CharField(blank=True, help_text='FHIR Patient or Practitioner resource ID', max_length=255, null=True),
        ),
    ]
