# Generated by Django 6.0.3 on 2026-04-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appointment_fhir_last_synced_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('in-person', 'In-Person'), ('follow-up', 'Follow-up'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Meeting URL for virtual consultations'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for consultation request'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed (Consultation Request)'), ('requested', 'Requested (Pending Doctor Review)'), ('booked', 'Booked (Confirmed)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20),
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
