# Generated by Django 6.0.3 on 2026-03-06 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_doctors_advancedirective_allergy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRResourceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Patient', 'Patient'), ('Practitioner', 'Practitioner'), ('Appointment', 'Appointment'), ('Observation', 'Observation'), ('DiagnosticReport', 'DiagnosticReport'), ('Medication', 'Medication'), ('MedicationRequest', 'MedicationRequest'), ('ServiceRequest', 'ServiceRequest'), ('DocumentReference', 'DocumentReference')], max_length=50)),
                ('local_object_id', models.CharField(max_length=100)),
                ('fhir_resource_id', models.CharField(blank=True, max_length=100)),
                ('fhir_server_url', models.URLField()),
                ('fhir_payload', models.JSONField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FHIR Resource Log',
                'verbose_name_plural': 'FHIR Resource Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=100, unique=True)),
                ('accession_number', models.CharField(blank=True, max_length=50)),
                ('modality', models.CharField(choices=[('CT', 'Computed Tomography'), ('MR', 'Magnetic Resonance'), ('XC', 'X-Ray'), ('US', 'Ultrasound'), ('PET', 'Positron Emission Tomography'), ('NM', 'Nuclear Medicine'), ('OT', 'Other')], max_length=10)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('study_date', models.DateField()),
                ('study_time', models.TimeField(blank=True, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('referring_physician', models.CharField(blank=True, max_length=255)),
                ('performing_physician', models.CharField(blank=True, max_length=255)),
                ('file_path', models.FileField(upload_to='dicom_studies/%Y/%m/')),
                ('file_size_mb', models.FloatField(default=0)),
                ('number_of_images', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('archived', 'Archived')], default='uploaded', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordering_doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_dicom_studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='dicom_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=100)),
                ('series_number', models.IntegerField()),
                ('series_description', models.CharField(blank=True, max_length=255)),
                ('number_of_instances', models.IntegerField(default=1)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('bits_allocated', models.IntegerField(blank=True, null=True)),
                ('bits_stored', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='accounts.dicomstudy')),
            ],
            options={
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='HL7Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('ADT', 'Admit, Discharge, Transfer'), ('ORM', 'Order Message'), ('ORU', 'Observation Result'), ('RGV', 'Pharmacy/Give'), ('MDM', 'Medical Document Management'), ('LAB', 'Laboratory'), ('SCH', 'Scheduling')], max_length=10)),
                ('message_control_id', models.CharField(max_length=100, unique=True)),
                ('message_version', models.CharField(default='2.5', max_length=10)),
                ('raw_message', models.TextField()),
                ('message_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error'), ('archived', 'Archived')], default='received', max_length=20)),
                ('sending_application', models.CharField(blank=True, max_length=255)),
                ('sending_facility', models.CharField(blank=True, max_length=255)),
                ('receiving_application', models.CharField(blank=True, max_length=255)),
                ('receiving_facility', models.CharField(blank=True, max_length=255)),
                ('message_datetime', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_hl7_messages', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hl7_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['message_type', 'message_status'], name='accounts_hl_message_5d9557_idx'), models.Index(fields=['patient', 'received_at'], name='accounts_hl_patient_bae0d5_idx')],
            },
        ),
    ]
