# Generated by Django 6.0.4 on 2026-04-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('chief-complaint', 'Chief Complaint'), ('history-present-illness', 'History of Present Illness'), ('physical-exam', 'Physical Examination'), ('assessment-plan', 'Assessment & Plan'), ('progress-note', 'Progress Note'), ('follow-up-note', 'Follow-up Note')], default='progress-note', max_length=30)),
                ('content', models.TextField()),
                ('vital_signs', models.JSONField(blank=True, default=dict, help_text='Store vital signs snapshot: temp, HR, BP, RR, SpO2, weight')),
                ('medications_reviewed', models.TextField(blank=True, help_text='Current medications discussed')),
                ('allergies_reviewed', models.TextField(blank=True, help_text='Allergies reviewed with patient')),
                ('is_final', models.BooleanField(default=True, help_text='True if this is final documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_full_name', models.CharField(blank=True, max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='accounts.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_level', models.CharField(choices=[('resuscitation', 'Resuscitation (Level 1)'), ('emergency', 'Emergency (Level 2)'), ('urgent', 'Urgent (Level 3)'), ('semi-urgent', 'Semi-Urgent (Level 4)'), ('non-urgent', 'Non-Urgent (Level 5)')], max_length=20)),
                ('overall_score', models.IntegerField(help_text='Overall score 1-100')),
                ('chief_complaint_severity', models.IntegerField(default=0, help_text='0-10 scale')),
                ('vital_signs_severity', models.IntegerField(default=0, help_text='0-10 scale')),
                ('mental_status_severity', models.IntegerField(default=0, help_text='0-10 scale')),
                ('pain_level', models.IntegerField(default=0, help_text='0-10 visual pain scale')),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('assessment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_scores', to='accounts.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_triage_scores', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='triage_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Triage Scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEventTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('appointment', 'Appointment'), ('lab-result', 'Lab Result'), ('imaging-study', 'Imaging Study'), ('prescription', 'Prescription'), ('consultation-note', 'Consultation Note'), ('referral', 'Referral'), ('vital-signs', 'Vital Signs'), ('admission', 'Hospital Admission'), ('discharge', 'Hospital Discharge'), ('allergy-reported', 'Allergy Reported'), ('medication-change', 'Medication Change'), ('other', 'Other Event')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('is_critical', models.BooleanField(default=False, help_text='Highlight as critical event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.appointment')),
                ('consultation_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.consultationnote')),
                ('dicom_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dicomstudy')),
                ('lab_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.labresult')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_timeline', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.prescription')),
            ],
            options={
                'verbose_name_plural': 'Patient Event Timelines',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['patient', 'event_date'], name='accounts_pa_patient_a4f74c_idx'), models.Index(fields=['event_type'], name='accounts_pa_event_t_033f90_idx')],
            },
        ),
    ]
