# Generated by Django 5.2.11 on 2026-04-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_appointment_is_virtual_appointment_location_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='components',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='critical_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='panel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abnormal', 'Abnormal'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
    ]
