# Generated by Django 5.2.12 on 2026-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fhirresourcelog_dicomstudy_dicomseries_hl7message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='local_folder_path',
            field=models.CharField(blank=True, help_text="Local pathway to DICOM folder on the doctor's machine", max_length=500),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='dicom_studies/%Y/%m/'),
        ),
    ]
