# Generated by Django 6.0.3 on 2026-04-16 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('doctor', 'Doctor Consultation'), ('imaging', 'Imaging Session'), ('lab', 'Lab Test / Sample Collection'), ('follow-up', 'Follow-up Appointment')], default='doctor', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='imaging_modality',
            field=models.CharField(blank=True, choices=[('MR', 'MRI'), ('CT', 'CT Scan'), ('XR', 'X-Ray'), ('US', 'Ultrasound'), ('PET', 'PET Scan'), ('NM', 'Nuclear Medicine'), ('DXA', 'Bone Density'), ('MG', 'Mammography'), ('RF', 'Fluoroscopy'), ('OT', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='accounts.appointment'),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
