# Generated by Django 6.0.3 on 2026-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_out_of_office',
            field=models.BooleanField(default=False),
        ),
    ]
