# Generated by Django 6.0.3 on 2026-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctorprofile_is_out_of_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_virtual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location_room',
            field=models.CharField(blank=True, default='Room 101', max_length=50),
        ),
    ]
